version: '3'

services:
  maildev:
    container_name: maildev
    image: maildev/maildev
    restart: "no"
    environment:
      - TZ=Australia/Sydney
      # - MAILDEV_WEB_PORT=1080
      # - MAILDEV_SMTP_PORT=1025
    ports:
      - ${PORT_WEB}:1080
      - ${PORT_SMTP}:1025
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
